'use client'
import {useEffect,useState} from 'react';import {useFD} from '@/lib/store';import {nf} from '@/components/charts'
export default function Inc(){const {frames,events,scn,demo}=useFD();const [gen,setGen]=useState(false),[busy,setBusy]=useState(false)
const go=()=>{setBusy(true);setTimeout(()=>{setBusy(false);setGen(true)},1200)};useEffect(()=>{if(demo>=0&&!gen&&!busy)go()},[demo])
if(!frames.length)return<p>Starting…</p>;const l=frames[frames.length-1],pk=(k:string)=>Math.max(...frames.map((f:any)=>f[k])),mit=events.filter((e:any)=>e.kind==='mitigation'),att=events.filter((e:any)=>e.kind==='attack'),res=events.filter((e:any)=>e.kind==='resilience'),rk=events.find((e:any)=>e.risk)
const clk=(t:number)=>new Date(Date.now()-(l.t-t)*1000).toLocaleTimeString('en-GB')
const inc=[...(att.length?[{sev:'CRITICAL',c:'bad',t:att[att.length-1].t,title:`${scn.replace('_',' ')} detected`,camp:rk?.risk?.campaign_id||'—',ev:rk?.risk?.evidence.join(', ')||'behavioral signals',mit:mit.length?mit[0].text:'pending',alloc:`${l.allocLegit} legit / ${l.allocBot} automated`,sys:l.state}]:[]),...(res.length?[{sev:'WARNING',c:'warn',t:res[res.length-1].t,title:'Resilience controls engaged',camp:'—',ev:`load ${(l.load*100).toFixed(0)}%`,mit:res[res.length-1].text,alloc:'inventory invariant '+(l.integrity?'held':'VIOLATED'),sys:`breaker ${l.breaker}`}]:[])]
const ctx:[string,string][]=[['Scenario',scn],['Window',frames.length+'s of telemetry'],['Peak requests/sec',nf(pk('rps'))],['Peak automated req/sec',nf(pk('bot'))],['Campaign clusters',String(pk('campaigns'))],['Mitigation events',String(mit.length)],['Peak p99 latency',pk('p99')+' ms'],['Allocated legit / automated',`${l.allocLegit} / ${l.allocBot}`],['Inventory invariant',l.integrity?'holds':'VIOLATED'],['Final state',l.state]]
return<div className="g"><div className="g">{inc.map((i,k)=><div key={k} className={'evt '+(i.c==='bad'?'':'warn')}><div><span className={'pill '+i.c}>{i.c==='bad'?'■':'▲'} {i.sev}</span><div className="mono mut" style={{fontSize:'.7rem',marginTop:'.4rem'}}>{clk(i.t)}</div></div><div><b>{i.title}</b><div className="mut" style={{fontSize:'.82rem',lineHeight:1.6}}>Campaign <span className="mono">{i.camp}</span> · Evidence: {i.ev}<br/>Mitigation: {i.mit}<br/>Allocation impact: {i.alloc} · System: {i.sys}</div></div></div>)}{!inc.length&&<div className="card"><span className="mut">No incidents in the current window. Start an attack in the Attack Lab or run the demo.</span></div>}</div>
<div className="g g2"><div className="card s-metric ok"><h2><span className="pill ok">● OBSERVED TELEMETRY</span> structured incident context</h2><div className="tw"><table><tbody>{ctx.map(([k,v])=><tr key={k}><td className="mut">{k}</td><td className="mono">{v}</td></tr>)}</tbody></table></div></div>
<div className="card s-metric ai"><h2><span className="pill ai">▲ AI-GENERATED INTERPRETATION</span></h2><p className="mut">Never operational truth. Mock generator in this build (no LLM connected) — it only restates the context on the left.</p><button className="btn pri" onClick={go} disabled={busy}>{busy?'Generating…':'Generate incident report'}</button>
{gen&&<div role="status" style={{animation:'rise .5s'}}><p><b>What happened.</b> Under “{scn}”, traffic peaked at {nf(pk('rps'))} req/s with up to {nf(pk('bot'))} req/s classified automated.</p><p><b>Coordinated behavior.</b> {pk('campaigns')} behavioral-correlation cluster(s) inferred; this indicates coordinated activity, not proven real-world identity.</p><p><b>Mitigation.</b> {mit.length} mitigation event(s) logged and traceable in the stream.</p><p><b>Allocation &amp; integrity.</b> {l.allocLegit} seats to legitimate and {l.allocBot} to automated entries; invariant {l.integrity?'held':'was VIOLATED'}.</p><p><b>Recovery.</b> Current state: {l.state}.</p><p className="mut">Sources: observed telemetry table (left).</p></div>}</div></div></div>}
