'use client'
import {useEffect,useMemo,useRef,useState} from 'react';import {runExperiment,XO} from '@/lib/fairness';import {Stack} from '@/components/charts'
const pc=(x:number)=>(x*100).toFixed(1)+'%',pp=(x:number)=>(x>=0?'+':'')+(x*100).toFixed(1)+' pp'
const Dots=({bot,e,seats}:{bot:number;e:number;seats:number})=>{const nb=Math.round(bot*100);return<div className="dots" aria-hidden="true">{Array.from({length:100},(_,k)=><i key={k} className={k>e*100?'':k<nb?'b':'l'}/>)}</div>}
export default function Fairness(){const [o,setO]=useState<XO>({legit:4000,botAcc:300,mult:5,seats:500,detect:.85,seed:42,formula:'proportional'}),[p,setP]=useState(1),[run,setRun]=useState(false),[cfg,setCfg]=useState(false),id=useRef<any>(null)
const r=useMemo(()=>runExperiment(o),[o]),set=(k:string,v:any)=>setO({...o,[k]:v}),e=1-Math.pow(1-p,3)
const go=()=>{clearInterval(id.current);setP(0);setRun(true);let i=0;id.current=setInterval(()=>{i++;setP(Math.min(1,i/36));if(i>=36){clearInterval(id.current);setRun(false)}},100)};useEffect(()=>{go();return()=>clearInterval(id.current)},[])
const W=(x:any,l:string)=><div><div className="eyebrow">{l}</div><Dots bot={x.share} e={e} seats={o.seats}/><div style={{height:'.5rem'}}/><Stack label={l} parts={[{label:'Legitimate',v:Math.round(x.legit*e),c:'var(--ok)'},{label:'Automated',v:Math.round(x.bot*e),c:'var(--bad)'}]}/></div>
const Big=({l,v,c,w}:{l:string;v:string;c:string;w:number})=><div className="card s-metric" style={{borderLeftColor:c}}><div className="eyebrow">{l}</div><div className="mono" style={{fontSize:'clamp(1.8rem,4vw,2.8rem)',fontWeight:600,color:c}}>{run?'…':v}</div><div className="bar"><span style={{width:Math.min(100,Math.abs(w)*200*e)+'%',background:c}}/></div></div>
return<div className="g"><div className="chips" style={{alignItems:'center'}}><span className="chip"><b>COUNTERFACTUAL EXPERIMENT</b></span><span className="chip sim">Simulation data · seed {o.seed}</span><span className="grow"/><button className="btn" onClick={()=>setCfg(!cfg)} aria-expanded={cfg}>Configure</button><button className="btn pri" onClick={go} disabled={run}>{run?'Running…':'Run experiment'}</button></div>
{cfg&&<div className="card"><h2>Configuration</h2><div className="chips" style={{gap:'1rem'}}>{[['legit','Legit users'],['botAcc','Bot accounts'],['mult','Sessions / bot'],['seats','Seats'],['seed','Seed']].map(([k,l])=><label key={k}>{l}<br/><input type="number" style={{width:100}} value={(o as any)[k]} onChange={ev=>set(k,Math.max(1,+ev.target.value))}/></label>)}<label>Detection rate {pc(o.detect)}<br/><input type="range" min="0" max="1" step=".05" value={o.detect} onChange={ev=>set('detect',+ev.target.value)}/></label><label>AAA baseline<br/><select value={o.formula} onChange={ev=>set('formula',ev.target.value)}><option value="proportional">Bot accounts ÷ all accounts</option><option value="worldA">Bot share in World A</option></select></label></div></div>}
<div className="g g2"><div className="card s-exp"><h2>World A · legitimate only</h2>{W(r.A,'Fair lottery')}</div><div className="card s-exp b"><h2>World B · same users + adversarial traffic</h2><div className="g">{W(r.N,'Naive fastest-request allocation')}{W(r.F,'FAIR DROP · dedupe + detection + lottery')}</div></div></div>
<div className="g g3"><Big l="Attack Allocation Advantage · naive" v={pp(r.aaaN)} c="var(--bad)" w={r.aaaN}/><Big l="Attack Allocation Advantage · FAIR DROP" v={pp(r.aaaF)} c="var(--ok)" w={r.aaaF}/><Big l="Queue distortion · naive / FAIR DROP" v={pc(r.N.distortion)+' / '+pc(r.F.distortion)} c="var(--ai)" w={r.N.distortion}/></div>
<div className="card"><h2>Measured comparison (accessible table)</h2><div className="tw"><table><thead><tr><th>Metric</th><th>World A</th><th>B · naive</th><th>B · FAIR DROP</th></tr></thead><tbody><tr><td>Human allocation rate</td><td>{pc(r.A.legit/o.seats)}</td><td>{pc(r.N.legit/o.seats)}</td><td>{pc(r.F.legit/o.seats)}</td></tr><tr><td>Automated allocation rate</td><td>{pc(r.A.share)}</td><td>{pc(r.N.share)}</td><td>{pc(r.F.share)}</td></tr><tr><td>Attack displacement (legit seats lost vs A)</td><td>0</td><td>{r.A.legit-r.N.legit}</td><td>{r.A.legit-r.F.legit}</td></tr><tr><td>Duplicate allocations</td><td>{r.A.dupClusters}</td><td>{r.N.dupClusters}</td><td>{r.F.dupClusters}</td></tr><tr><td>Overselling</td><td>{r.A.oversell}</td><td>{r.N.oversell}</td><td>{r.F.oversell}</td></tr></tbody></table></div><p className="mut" style={{fontSize:'.8rem'}}>Flagged clusters {r.entries.flaggedClusters}/{o.botAcc}; eligible entries after enforcement {r.entries.eligibleFair}. Results hold only for this simulated model; they are not benchmark claims.</p></div></div>}
