'use client'
import Link from 'next/link';import {useFD} from '@/lib/store';import {Area,Stack,Kpi,nf} from '@/components/charts';import {Pipeline} from '@/components/Pipeline'
export default function Home(){const {frames,last:l,scn}=useFD()
return<div className="g"><section className="card s-hero"><div className="chips"><span className="chip"><b>DROP #FD-2026-001</b></span><span className="chip ok">● LIVE</span><span className="chip"><b>500</b> seats</span><span className="chip"><b>50K+</b> clients · scenario target</span><span className="chip">Queue active</span><span className="chip sim">Simulation data</span></div>
<h2 className="disp" style={{margin:'1rem 0 .4rem',fontSize:'clamp(2.6rem,9vw,5.8rem)',letterSpacing:'-.045em',color:'var(--tx)',textTransform:'none',fontFamily:'inherit'}}>FAIR <em>DROP</em></h2>
<p style={{fontSize:'clamp(1.1rem,2.4vw,1.6rem)',margin:'0 0 .8rem',fontWeight:600}}>Fair access under adversarial load.</p>
<p className="mono mut" style={{margin:'0 0 .6rem'}}>500 seats. 50,000+ users. Coordinated automation.</p>
<p className="mut" style={{maxWidth:640,lineHeight:1.6}}>We don’t make users race bots. <b style={{color:'var(--tx)'}}>We remove the race.</b> Legitimate users enter a controlled pre-queue; behavioral intelligence correlates coordinated abuse; deterministic policy adapts admission; allocation is server-authoritative and cryptographically verifiable — and fairness is measured, not claimed.</p>
<div className="chips" style={{marginTop:'1.4rem'}}><Link className="btn pri" href="/drop">Enter drop</Link><Link className="btn" href="/control">Control center</Link><Link className="btn" href="/fairness">Fairness lab</Link></div></section>
<section><div className="eyebrow" style={{margin:'.4rem 0'}}>System thesis · controlled flow</div><Pipeline/></section>
{l&&<div className="g g21"><div className="card"><h2>Live traffic · {scn.replace('_',' ')} · simulation</h2><Area label="Traffic" series={[{k:'Legitimate',c:'var(--ok)',v:frames.map((f:any)=>f.legit)},{k:'Suspicious',c:'var(--warn)',v:frames.map((f:any)=>f.susp)},{k:'Automated',c:'var(--bad)',v:frames.map((f:any)=>f.bot)}]}/><Stack label="Traffic composition" parts={[{label:'Legitimate',v:l.legit,c:'var(--ok)'},{label:'Suspicious',v:l.susp,c:'var(--warn)'},{label:'Automated',v:l.bot,c:'var(--bad)'}]}/></div>
<div className="g"><Kpi l="Requests / sec" v={nf(l.rps)}/><Kpi l="Queue depth" v={nf(l.queue)}/><Kpi l="Seats remaining" v={l.seats.avail}/></div></div>}
<div className="g g3">{[['Designed to reduce speed advantage','Refreshes and parallel requests cannot become the allocation mechanism.'],['Server-authoritative','Client queue and seat state is never trusted; ML never mutates inventory.'],['Measured, not claimed','Counterfactual World A vs World B quantifies attack allocation advantage.']].map(([a,b])=><div key={a} className="card s-metric"><b>{a}</b><p className="mut" style={{margin:'.4rem 0 0'}}>{b}</p></div>)}</div></div>}
