export const nf=(n:number)=>n.toLocaleString('en-US')
export function Spark({v,color='var(--acc)',h=56,label}:{v:number[];color?:string;h?:number;label:string}){const w=200,mx=Math.max(1,...v),n=Math.max(1,v.length-1),pts=v.map((y,i)=>`${(i/n)*w},${h-3-(y/mx)*(h-8)}`).join(' ')
return<svg role="img" aria-label={`${label}: latest ${v[v.length-1]??0}, peak ${mx}`} viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{width:'100%',height:h}}><polygon points={`0,${h} ${pts} ${w},${h}`} fill={color} opacity=".15"/><polyline points={pts} fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>}
export function Stack({parts,label}:{parts:{label:string;v:number;c:string}[];label:string}){const T=parts.reduce((a,p)=>a+p.v,0)||1
return<div role="img" aria-label={label+': '+parts.map(p=>`${p.label} ${(p.v/T*100).toFixed(1)}%`).join(', ')}><div className="stack">{parts.map(p=><span key={p.label} style={{width:p.v/T*100+'%',background:p.c}}/>)}</div><div className="legend">{parts.map(p=><span key={p.label}><i style={{background:p.c}}/>{p.label} {nf(p.v)} ({(p.v/T*100).toFixed(1)}%)</span>)}</div></div>}
export const Pill=({s,children}:{s:'ok'|'warn'|'bad'|'acc';children:any})=><span className={'pill '+s}>{{ok:'✓',warn:'▲',bad:'■',acc:'●'}[s]} {children}</span>
export const Kpi=({l,v,s}:{l:string;v:any;s?:string})=><div className="card kpi"><div className="l">{l}</div><div className="v" aria-live="off">{v}</div>{s&&<div className="mut" style={{fontSize:'.75rem'}}>{s}</div>}</div>
export function Graph({campaigns,mult}:{campaigns:number;mult:number}){const k=Math.max(1,campaigns),cx=300,cy=150;const nodes:any[]=[]
for(let i=0;i<k;i++){const a=(i/k)*Math.PI*2-1.2,x=cx+Math.cos(a)*(k>1?95:0),y=cy+Math.sin(a)*(k>1?70:0);nodes.push({x,y,id:'C-'+(184+i)})}
return<svg role="img" aria-label={`Identity cluster graph: ${campaigns} campaign cluster(s), each linking accounts, sessions, tokens and a shared behavioral fingerprint`} viewBox="0 0 600 300" style={{width:'100%'}}>{nodes.map((n,i)=>{const kids=Array.from({length:Math.min(6,mult+2)},(_,j)=>{const a=(j/Math.min(6,mult+2))*Math.PI*2+i;return{x:n.x+Math.cos(a)*(k>1?50:110),y:n.y+Math.sin(a)*(k>1?36:80),t:['Account','Session','Token','Behavior'][j%4]}})
return<g key={i}>{kids.map((c,j)=><g key={j}><line x1={n.x} y1={n.y} x2={c.x} y2={c.y} stroke="var(--ai)" strokeDasharray="3 3" opacity=".8" className="flow"/><circle cx={c.x} cy={c.y} r="9" fill="var(--s2)" stroke="var(--acc)"/><text x={c.x} y={c.y+22} fontSize="8" textAnchor="middle" fill="var(--mut)">{c.t}</text></g>)}<circle cx={n.x} cy={n.y} r="16" fill="var(--s2)" stroke="var(--warn)" strokeWidth="2" className="live"/><text x={n.x} y={n.y+3} fontSize="8" textAnchor="middle" fill="var(--tx)">{n.id}</text></g>})}{campaigns===0&&<text x="300" y="150" textAnchor="middle" fill="var(--mut)" fontSize="13">No coordinated activity correlated yet</text>}</svg>}

export function Area({series,label,h=210}:{series:{k:string;c:string;v:number[]}[];label:string;h?:number}){const W=640,n=Math.max(2,series[0].v.length),tot=Array.from({length:n},(_,i)=>series.reduce((a,s)=>a+(s.v[i]||0),0)),mx=Math.max(1,...tot)*1.12,X=(i:number)=>i/(n-1)*W,Y=(v:number)=>h-20-(v/mx)*(h-34);let base=new Array(n).fill(0)
const ls=series.map(s=>{const top=Array.from({length:n},(_,i)=>base[i]+(s.v[i]||0)),d='M'+top.map((y,i)=>X(i)+','+Y(y)).join('L')+'L'+[...base].reverse().map((y,i)=>X(n-1-i)+','+Y(y)).join('L')+'Z';base=top;return{d,c:s.c,k:s.k}})
return<svg role="img" aria-label={label+': '+series.map(s=>s.k+' '+nf(s.v[s.v.length-1]||0)).join(', ')+' requests per second now'} viewBox={`0 0 ${W} ${h}`} style={{width:'100%',height:'auto'}}>{[0,.25,.5,.75,1].map(f=><g key={f}><line x1="0" x2={W} y1={Y(mx/1.12*f)} y2={Y(mx/1.12*f)} stroke="var(--line)"/><text x="4" y={Y(mx/1.12*f)-3} fontSize="9" fill="var(--mut2)" fontFamily="monospace">{nf(Math.round(mx/1.12*f))}</text></g>)}{ls.map(l=><path key={l.k} d={l.d} fill={l.c} opacity=".38"/>)}{ls.map((l,i)=>{const t=series.slice(0,i+1).reduce((a,s)=>a.map((x:number,j:number)=>x+(s.v[j]||0)),new Array(n).fill(0));return<polyline key={l.k} points={t.map((y:number,j:number)=>X(j)+','+Y(y)).join(' ')} fill="none" stroke={l.c} strokeWidth="1.6"/>})}</svg>}
