'use client'
import Link from 'next/link';import {usePathname,useRouter} from 'next/navigation';import {useEffect,useRef,useState} from 'react'
import {useFD} from '@/lib/store';import {setPref} from '@/lib/prefs';import {DEMO} from '@/lib/demo';import Ic from './Icon';import Ambient from './Ambient';import A11y from './A11y'
const G=[{h:'',i:[['/','Overview','home'],['/drop','Drop','drop']]},{h:'Intelligence',i:[['/control','Control Center','gauge'],['/attacks','Attack Lab','zap'],['/campaigns','Campaigns','net']]},{h:'Fairness',i:[['/fairness','Fairness Lab','scale'],['/allocations','Allocations','layers'],['/verify','Verification','shield']]},{h:'Operations',i:[['/incidents','Incidents','alert'],['/system','System','cpu'],['/settings','Settings','sliders']]}]
const ALL=G.flatMap(g=>g.i),BN=['/','/drop','/control','/attacks','/fairness']
export default function Shell({children}:{children:any}){const path=usePathname(),router=useRouter(),fd=useFD(),[theme,setTheme]=useState('dark'),[col,setCol]=useState(false),[dr,setDr]=useState(false),[q,setQ]=useState(''),[qo,setQo]=useState(false)
const T=useRef<any[]>([]),sr=useRef<HTMLInputElement>(null)
useEffect(()=>{setTheme(document.documentElement.dataset.theme||'dark');const k=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();sr.current?.focus()}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[])
useEffect(()=>{setDr(false)},[path])
const tog=()=>{const t=theme==='dark'?'light':'dark';setTheme(t);setPref('theme',t)}
const runDemo=()=>{T.current.forEach(clearTimeout);T.current=[];let at=0;DEMO.forEach((d,i)=>{T.current.push(setTimeout(()=>{fd.setDemo(i);fd.setCfg({vol:d.v,auto:null,mult:3});fd.setScn(d.s);router.push(d.p)},at));at+=9000});T.current.push(setTimeout(()=>fd.setDemo(-1),at))}
const endDemo=()=>{T.current.forEach(clearTimeout);fd.setDemo(-1)}
const cur=ALL.find(a=>a[0]===path)||ALL[0],res=ALL.filter(a=>a[1].toLowerCase().includes(q.toLowerCase()))
const Nav=()=><>{G.map((g,gi)=><div key={gi} className="ng">{g.h&&<div className="nvh eyebrow">{g.h}</div>}{g.i.map(([h,l,ic])=><Link key={h} href={h} className="nv" aria-current={path===h?'page':undefined} title={l}><Ic n={ic}/><span className="nl">{l}</span></Link>)}</div>)}</>
return<div className={'app'+(col?' col':'')}><a href="#main" className="sr">Skip to content</a><Ambient/>
<aside className="side"><div className="brand"><svg width="30" height="30" viewBox="0 0 32 32" aria-hidden="true"><rect x="1" y="1" width="30" height="30" rx="5" fill="none" stroke="var(--sys)" strokeWidth="1.5"/><path d="M6 9h20M6 16h14M6 23h8" stroke="var(--tx)" strokeWidth="2" strokeLinecap="round"/><circle cx="24" cy="16" r="2.6" fill="var(--sys)"/><circle cx="18" cy="23" r="2.6" fill="var(--ok)"/></svg><div className="nl"><b>FAIR DROP</b><span className="eyebrow">Adversarial allocation intelligence</span></div></div>
<nav aria-label="Primary" className="navs"><Nav/></nav><div className="sfoot"><div className="live-chip nl"><i className="dot live"/> <span><b>DROP LIVE</b><br/><span className="mono mut">#FD-2026-001</span></span></div><button className="btn ghost" onClick={()=>setCol(!col)} aria-label="Collapse sidebar"><Ic n="menu" s={15}/><span className="nl">COLLAPSE</span></button></div></aside>
{dr&&<div className="drawer" onClick={()=>setDr(false)}><div className="dpan" onClick={e=>e.stopPropagation()}><Nav/></div></div>}
<div className="wrap"><header className="top"><div className="crumb"><span className="eyebrow">FAIR DROP / {cur[1].toUpperCase()}</span><h1>{cur[1]}</h1></div>
<div className="search"><Ic n="search" s={15}/><input ref={sr} value={q} onChange={e=>{setQ(e.target.value);setQo(true)}} onFocus={()=>setQo(true)} onBlur={()=>setTimeout(()=>setQo(false),150)} onKeyDown={e=>{if(e.key==='Enter'&&res[0]){router.push(res[0][0]);setQ('');setQo(false)}}} placeholder="Jump to… (Ctrl K)" aria-label="Command search"/>{qo&&q&&<div className="cmdk">{res.map(r=><Link key={r[0]} href={r[0]} onClick={()=>setQ('')}><Ic n={r[2]} s={14}/> {r[1]}</Link>)}{!res.length&&<span className="mut">No match</span>}</div>}</div>
<span className="grow"/><span className="pill sim hide-s">◆ SIMULATION MODE</span>{fd.demo>=0?<span className="pill ai"><i className="dot live"/> DEMO {String(fd.demo+1).padStart(2,'0')}/09</span>:<span className="pill ok hide-s"><i className="dot live"/> LIVE · FD-2026-001</span>}
<button className="ib" onClick={tog} aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`}><Ic n={theme==='dark'?'sun':'moon'} s={17}/></button>
<button className="btn pri" onClick={fd.demo>=0?endDemo:runDemo}><Ic n="play" s={13}/> <span className="hide-s">{fd.demo>=0?'STOP DEMO':'RUN FAIR DROP DEMO'}</span><span className="show-s">DEMO</span></button></header>
<main id="main" tabIndex={-1} style={{paddingBottom:fd.demo>=0?'120px':undefined}}><div key={path} className="page">{children}</div></main></div>
{fd.demo>=0&&<div className="demo" role="status"><div><span className="eyebrow ai">● DEMO — PHASE {String(fd.demo+1).padStart(2,'0')} / 09</span><b className="mono" style={{display:'block'}}>{DEMO[fd.demo].label}</b><span className="mut" style={{fontSize:'.8rem'}}>{DEMO[fd.demo].t}</span></div><button className="btn" onClick={endDemo}>STOP</button><i className="dprog" style={{width:((fd.demo+1)/9*100)+'%'}}/></div>}
<nav className="bnav" aria-label="Quick navigation">{ALL.filter(a=>BN.includes(a[0])).map(([h,l,ic])=><Link key={h} href={h} aria-current={path===h?'page':undefined}><Ic n={ic} s={19}/><span>{l.split(' ')[0]}</span></Link>)}<button onClick={()=>setDr(true)} aria-label="More pages"><Ic n="menu" s={19}/><span>More</span></button></nav>
<A11y bottom/></div>}
