'use client'
import {useFD} from '@/lib/store';import {Area,Stack,Spark,Kpi,Pill,nf} from '@/components/charts';import {Topology} from '@/components/Pipeline';import {SCN} from '@/lib/sim'
const sc:any={HEALTHY:'ok',ELEVATED:'acc',SATURATED:'warn',DEGRADED:'bad',RECOVERING:'ok'},ST=['HEALTHY','ELEVATED','SATURATED','DEGRADED','RECOVERING']
export default function Control(){const {frames,last:l,events,scn,setScn}=useFD();if(!l)return<p className="mono">Starting simulator…</p>
const m=(k:string)=>frames.map((f:any)=>f[k]),clk=(t:number)=>new Date(Date.now()-(l.t-t)*1000).toLocaleTimeString('en-GB')
return<div className="g"><div className="chips" style={{alignItems:'center'}}><span className="chip"><b>DROP #FD-2026-001</b></span><span className="chip"><b>500</b> seats</span><span className="chip sim">Simulation data</span><Pill s={sc[l.state]}>{l.state}</Pill><span className="grow"/><label className="chip">Scenario <select value={scn} onChange={e=>setScn(e.target.value)}>{Object.entries(SCN).map(([k,v]:any)=><option key={k} value={k}>{v.label}</option>)}</select></label></div>
{!l.integrity&&<div className="card bad" role="alert"><b>■ INVENTORY INTEGRITY VIOLATION REPORTED</b></div>}
<div className="card"><div className="row" style={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:'1rem'}}><h2>Live traffic</h2><div className="mono"><span style={{fontSize:'2rem',fontWeight:600}}>{nf(l.rps)}</span> <span className="mut">REQ/S</span></div></div><Area label="Live traffic by class" series={[{k:'Legitimate',c:'var(--ok)',v:m('legit')},{k:'Suspicious',c:'var(--warn)',v:m('susp')},{k:'Automated',c:'var(--bad)',v:m('bot')}]}/><Stack label="Traffic composition" parts={[{label:'Legitimate',v:l.legit,c:'var(--ok)'},{label:'Suspicious',v:l.susp,c:'var(--warn)'},{label:'Automated',v:l.bot,c:'var(--bad)'}]}/></div>
<div className="g g4"><div className="card s-metric kpi"><div className="l">Requests / sec</div><div className="v">{nf(l.rps)}</div><Spark v={m('rps')} h={28} label="rps"/></div><div className="card s-metric ai kpi"><div className="l">Queue depth</div><div className="v">{nf(l.queue)}</div><Spark v={m('queue')} h={28} color="var(--ai)" label="queue"/></div><div className="card s-metric kpi"><div className="l">Active sessions</div><div className="v">{nf(l.sessions)}</div></div><div className="card s-metric ok kpi"><div className="l">Seats remaining</div><div className="v">{l.seats.avail}</div><div className="mut mono" style={{fontSize:'.7rem'}}>{l.seats.held} held · {l.seats.confirmed} confirmed</div></div></div>
<div className="card"><h2>System state · request path</h2><Topology l={l}/></div>
<div className="g g2"><div className="card"><h2>Live event stream</h2><div className="tl" aria-live="polite">{events.map((e:any)=><div key={e.id}><span className="mut">{clk(e.t)}</span> <span className={e.sev==='bad'?'bad':e.sev==='warn'?'warn':e.sev==='ok'?'ok':'acc'}>{{bad:'●',warn:'▲',ok:'✓',info:'●'}[e.sev as 'bad']}</span> {e.text}</div>)}{!events.length&&<span className="mut">Waiting for events…</span>}</div></div>
<div className="card"><h2>Latency (ms) · p50 / p95 / p99</h2><div className="tw"><table><tbody>{[['p50','var(--sys)'],['p95','var(--warn)'],['p99','var(--bad)']].map(([k,c])=><tr key={k}><td>{k}</td><td className="mono">{l[k]}</td><td style={{width:'60%'}}><Spark v={m(k)} h={26} color={c} label={k}/></td></tr>)}</tbody></table></div>
<h3 style={{marginTop:'1rem'}}>Resilience</h3><div className="steps">{ST.map(s=><span key={s} className={'step '+(s===l.state?'on':'')} aria-current={s===l.state}>{s===l.state?'● ':'○ '}{s}</span>)}</div><p className="mono mut" style={{fontSize:'.76rem'}}>load {(l.load*100).toFixed(0)}% · throttle {l.throttle?'▲ on':'off'} · shed {(l.shed*100).toFixed(0)}% · breaker {l.breaker}</p>
<h3>Risk distribution</h3><Stack label="Risk distribution" parts={[{label:'LOW',v:l.risk[0],c:'var(--ok)'},{label:'ELEVATED',v:l.risk[1],c:'var(--warn)'},{label:'HIGH',v:l.risk[2],c:'var(--bad)'},{label:'QUARANTINED',v:l.risk[3],c:'var(--ai)'}]}/></div></div></div>}
