'use client'
import {useState} from 'react';import {useFD} from '@/lib/store';import {SCN,PH} from '@/lib/sim';import {Graph,Stack,nf} from '@/components/charts';import {Pipeline} from '@/components/Pipeline'
export default function Attacks(){const {scn,setScn,cfg,setCfg,last:l,events}=useFD(),[open,setOpen]=useState(false);const t=l?l.t:0,att=!['NORMAL','FLASH_CROWD','RECOVERY'].includes(scn),ad=scn==='ADAPTIVE'
const steps:any[]=ad?[[0,'ph','⚡',PH[0],'Maximum request rate'],[8,'df','▼','Defense activated','Rate-based policy engages'],[15,'ph','◌',PH[1],'Human-like timing to evade rules'],[22,'df','▼','Behavioral correlation','Timing + sequence similarity'],[30,'ph','◎',PH[2],'Identity multiplication across sessions'],[40,'df','▼','Mitigation','Identity-cluster eligibility enforced']]:[[0,'ph','⚡',SCN[scn].label,SCN[scn].blurb],[6,'df','▼','Defense activated','Behavioral signals escalate risk'],[9,'df','▼','Behavioral correlation','Coordinated activity clustered'],[12,'df','▼','Mitigation','Policy reduces admission weight']]
const shown=att?steps.filter(s=>t>=s[0]):[],cur=shown.length-1
const phIdx=(i:number)=>steps.slice(0,i+1).filter(s=>s[1]==='ph').length-1
return<div className="g"><div className="chips" style={{alignItems:'center'}}><span className="chip"><b>ATTACK CAMPAIGN #184</b></span><span className="chip sim">Simulated adversary — no real traffic</span><span className="grow"/><button className="btn" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?'Hide':'Configure'} attack</button></div>
{open&&<div className="g g2"><div className="card"><h2>Scenario</h2><div role="radiogroup" aria-label="Attack scenario" className="g" style={{gap:'.4rem'}}>{Object.entries(SCN).map(([k,v]:any)=><label key={k} className={'step '+(k===scn?'on':'')} style={{cursor:'pointer'}}><input type="radio" name="s" checked={k===scn} onChange={()=>setScn(k)}/> <b>{v.label}</b> <span className="mut">— {v.blurb}</span></label>)}</div></div>
<div className="card"><h2>Configuration</h2><label>Traffic volume ×{cfg.vol.toFixed(1)}<input type="range" min=".5" max="2.5" step=".1" value={cfg.vol} onChange={e=>setCfg({...cfg,vol:+e.target.value})}/></label><br/><br/><label>Automation share {cfg.auto==null?'(scenario default)':Math.round(cfg.auto*100)+'%'}<input type="range" min="0" max=".95" step=".05" value={cfg.auto??.4} onChange={e=>setCfg({...cfg,auto:+e.target.value})}/></label><br/><br/><label>Session multiplicity ×{cfg.mult}<input type="range" min="1" max="10" value={cfg.mult} onChange={e=>setCfg({...cfg,mult:+e.target.value})}/></label><p className="mut">Concurrency, retry behavior and strategy are fixed by the scenario in this build.</p></div></div>}
<div className="g g21"><div className="card"><div className="row"><h2>Attack progression</h2>{!att&&<button className="btn pri" onClick={()=>setScn('ADAPTIVE')}>Start adaptive attack</button>}{att&&<button className="btn" onClick={()=>setScn('NORMAL')}>Stop attack</button>}</div>
{!att?<p className="mut">No attack running. Start one to watch the attacker and defense co-evolve.</p>:<div className="tlv" aria-live="polite">{shown.map((s,i)=><div key={s[3]+i} className={'tn2 '+s[1]+(s[1]==='ph'&&(ad?phIdx(i)===l.phase:i===cur)&&i===cur||s[1]==='ph'&&ad&&phIdx(i)===l.phase&&cur>=i&&!shown.slice(i+1).some(x=>x[1]==='ph')?' cur':'')}><div className="eyebrow">{s[1]==='ph'?`PHASE 0${phIdx(i)+1}`:'DEFENSE'}</div><b style={{fontSize:'1.05rem'}}>{s[2]} {String(s[3]).toUpperCase()}</b><div className="mut" style={{fontSize:'.85rem'}}>{s[4]}</div>{s[1]==='ph'&&l&&i===shown.map(x=>x[1]).lastIndexOf('ph')&&<div className="mono bad" style={{marginTop:'.3rem'}}>{nf(l.bot)} automated req/s · {nf(l.risk[2]+l.risk[3])} flagged sessions</div>}</div>)}</div>}</div>
<div className="card"><h2>Identity cluster graph</h2><Graph campaigns={l?l.campaigns:0} mult={cfg.mult}/><p className="mut" style={{fontSize:'.8rem'}}>Behavioral correlation of accounts, sessions and tokens. Not proof of real-world identity.</p></div></div>
<div className="card"><h2>Defense pipeline</h2><Pipeline/></div>
<div className="g g2"><div className="card"><h2>Allocation impact (cumulative)</h2>{l&&<Stack label="Allocation" parts={[{label:'Legitimate',v:l.allocLegit,c:'var(--ok)'},{label:'Automated',v:l.allocBot,c:'var(--bad)'}]}/>}</div><div className="card"><h2>Latest risk evidence (RiskEvent)</h2><div className="tw">{events.filter((e:any)=>e.risk).slice(0,2).map((e:any)=><pre key={e.id} className="mono" style={{fontSize:'.68rem',margin:'.3rem 0'}}>{JSON.stringify(e.risk,null,1)}</pre>)}</div></div></div></div>}
