'use client'
import {useEffect,useState} from 'react';import {sha,entries,allocate} from '@/lib/proof';import {Pill} from '@/components/charts'
const N=2000,SEATS=500,IDS=entries(N),SEED0='fairdrop-demo-seed-7f3a91',NAMES=['COMMITMENT','SEED REVEALED','DETERMINISTIC SHUFFLE','ELIGIBLE ENTRIES','ALLOCATION','VERIFIED']
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms))
export default function Verify(){const [commit,setCommit]=useState(''),[seed,setSeed]=useState(SEED0),[w,setW]=useState<string[]>([]),[root,setRoot]=useState(''),[h,setH]=useState(''),[st,setSt]=useState<string[]>(Array(6).fill('PENDING')),[info,setInfo]=useState<string[]>(Array(6).fill('')),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
useEffect(()=>{(async()=>{setCommit(await sha(SEED0));setRoot(await sha(IDS.join(',')));const a=await allocate(SEED0,IDS,SEATS);setW(a.winners);setH(a.h)})()},[])
const verify=async()=>{setBusy(true);setMsg('');setSt(Array(6).fill('PENDING'));setInfo(Array(6).fill(''));const S=(i:number,v:string,t?:string)=>{setSt(a=>a.map((x,j)=>j===i?v:x));if(t!==undefined)setInfo(a=>a.map((x,j)=>j===i?t:x))}
S(0,'PROCESSING');await wait(500);const c=await sha(seed);if(c!==commit){S(0,'FAILED','SHA-256(seed) = '+c.slice(0,24)+'…  ≠  published '+commit.slice(0,24)+'…');setSt(a=>a.map((x,j)=>j>0?'HALTED':x));const a=await allocate(seed,IDS,SEATS),set=new Set(w),diff=a.winners.filter(x=>!set.has(x)).length;setMsg(`VERIFICATION FAILED — the revealed seed does not match the commitment published before entries closed. Using this seed would change ${diff} of ${SEATS} winners, so the allocation cannot be trusted.`);setBusy(false);return}
S(0,'VERIFIED','Hash matches published commitment');S(1,'PROCESSING');await wait(400);S(1,'VERIFIED','seed = '+seed.slice(0,18)+'…');S(2,'PROCESSING');await wait(500);const a=await allocate(seed,IDS,SEATS);S(2,'VERIFIED','key '+a.h.slice(0,24)+'…');S(3,'PROCESSING');await wait(400);const r2=await sha(IDS.join(','));S(3,r2===root?'VERIFIED':'FAILED',N+' entries · root '+r2.slice(0,16)+'…');S(4,'PROCESSING');await wait(500);const ok=a.winners.join()===w.join();S(4,ok?'VERIFIED':'FAILED',`${a.winners.length} / ${SEATS} allocated · identical to published result: ${ok?'yes':'no'}`);await wait(300);S(5,ok?'VERIFIED':'FAILED',ok?'Independent recomputation agrees':'');setBusy(false)}
return<div className="g"><div className="chips"><span className="chip sim">Demo proof · computed live in your browser (SHA-256 + seeded shuffle)</span><span className="chip">Production proof: GET /verify/{'{allocation}'}</span></div>
<div className="g g2"><div className="card s-ver"><h2>Published commitment</h2><div className="mono" style={{wordBreak:'break-all',background:'var(--s2)',padding:'.6rem',borderRadius:4,fontSize:'.8rem'}}>{commit||'…'}</div><br/><label className="eyebrow">Revealed seed — edit to tamper<br/><input style={{width:'100%',marginTop:'.3rem'}} value={seed} onChange={e=>setSeed(e.target.value)}/></label><div style={{marginTop:'1rem'}}><button className="btn pri" onClick={verify} disabled={busy}>{busy?'Verifying…':'Verify allocation'}</button></div>{msg&&<p role="alert" className="bad" style={{fontWeight:600}}>■ {msg}</p>}{st[5]==='VERIFIED'&&<p role="status"><Pill s="ok">ALLOCATION VERIFIED</Pill></p>}<p className="mut" style={{fontSize:'.8rem'}}>This shows allocation is auditable; it does not prove entry eligibility was correct.</p></div>
<div className="stg">{NAMES.map((n,i)=><div key={n} className={'sg '+st[i]}><span className="mono" style={{width:22}}>{st[i]==='VERIFIED'?'✓':st[i]==='FAILED'?'■':st[i]==='PROCESSING'?'●':'○'}</span><div style={{flex:1,minWidth:0}}><b className="mono" style={{fontSize:'.8rem',letterSpacing:'.1em'}}>{n}</b><div className="mut mono" style={{fontSize:'.7rem',wordBreak:'break-all'}}>{info[i]||(i===3?N+' eligible entries':'')}</div></div><span className={'pill '+(st[i]==='VERIFIED'?'ok':st[i]==='FAILED'?'bad':st[i]==='PROCESSING'?'acc':'')}>{st[i]}</span></div>)}</div></div></div>}
